/* ---------- views ---------- */
const TABS=[['feed','Ideas'],['people','People'],['chat','Chat'],['live','Live'],['me','Profile']];
function shell(){
  $('#hd').innerHTML=`<span class="logo" data-tab="feed">💡 ${esc(APP)}</span><nav>${TABS.map(([k,l])=>`<button data-tab="${k}">${l}${k==='live'?' (<span id="lc">'+Object.keys(online).length+'</span>)':''}</button>`).join('')}</nav>`;
  setTab(tab);
}
function setTab(t){if(map&&t!=='live'){map.remove();map=null;mapReady=false;spin=false}tab=t;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===t));scrollTo(0,0);
  ({feed:vFeed,people:vPeople,chat:vChat,live:vLive,me:vMe})[t]()}
function vFeed(){$('#main').innerHTML=`<div class="card"><input id="pt" placeholder="Idea title" maxlength="120"><textarea id="px" placeholder="Describe your idea…" maxlength="2000"></textarea><input id="pg" placeholder="Tag (e.g. tech, art)" maxlength="24"><div class="row"><label class="btn g" style="cursor:pointer">📷 Image<input type="file" id="pf" accept="image/*" hidden></label><span class="mu" id="pn"></span><span class="sp"></span><button class="btn" data-act="post">Share idea</button></div></div><input id="sq" placeholder="🔍 Search ideas" value="${esc(q)}"><div id="list"></div>`;paintFeed()}
function paintFeed(){const l=$('#list');if(!l)return;const f=posts.filter(p=>!q||(p.title+p.body+(p.tag||'')).toLowerCase().includes(q.toLowerCase()));
  l.innerHTML=f.map(p=>{const lk=p.likes.some(x=>x.user_id===me.id);return `<div class="card"><div class="row">${av(p.profiles)}<div><b>${esc(nm(p.profiles))}</b><div class="mu">${tm(p.created_at)}</div></div></div><h3>${esc(p.title)}</h3><div>${esc(p.body)}</div>${att(p.image_url)}<div class="row" style="margin-top:8px">${p.tag?`<span class="tag">#${esc(p.tag)}</span>`:''}<span class="sp"></span><button class="btn g" data-act="like" data-id="${p.id}">${lk?'❤️':'🤍'} ${p.likes.length}</button><button class="btn g" data-act="oc" data-id="${p.id}">💬 ${p.comments.length}</button>${p.user_id===me.id?`<button class="btn g" data-act="del" data-id="${p.id}">🗑</button>`:''}</div>${openC[p.id]?cmts(p):''}</div>`}).join('')||'<p class="mu">No ideas yet. Be the first!</p>'}
const cmts=p=>`<div style="margin-top:8px">${p.comments.sort((a,b)=>a.created_at<b.created_at?-1:1).map(c=>`<div class="row" style="border-top:1px solid var(--bd);padding:8px 0">${av(c.profiles)}<div><b>${esc(nm(c.profiles))}</b> <span class="mu">${tm(c.created_at)}</span><div>${esc(c.body)}</div></div></div>`).join('')}<div class="row"><input id="ci${p.id}" placeholder="Write a comment…" style="margin:0" maxlength="500"><button class="btn" data-act="cmt" data-id="${p.id}">Post</button></div></div>`;
function vPeople(){$('#main').innerHTML=`<input id="sq" placeholder="🔍 Search people" value="${esc(q)}"><div id="plist"></div>`;paintPeople()}
function paintPeople(){const l=$('#plist');if(!l)return;
  l.innerHTML=Object.values(people).filter(p=>p.id!==me.id&&(!q||(nm(p)+p.full_name+(p.bio||'')).toLowerCase().includes(q.toLowerCase()))).map(p=>{const f=fr.find(x=>(x.a===me.id&&x.b===p.id)||(x.b===me.id&&x.a===p.id));
    const b=!f?`<button class="btn" data-act="add" data-id="${p.id}">Add friend</button>`:f.status==='accepted'?`<button class="btn g" data-act="dm" data-id="${p.id}">Message</button>`:f.a===me.id?'<span class="mu">Request sent</span>':`<button class="btn" data-act="acc" data-id="${p.id}">Accept</button>`;
    return `<div class="card row">${av(p)}<div class="sp"><b>${esc(nm(p))}</b><div class="mu">${esc([p.role,p.city].filter(Boolean).join(' · '))}</div><div class="mu">${esc(p.bio||'')}</div></div>${b}</div>`}).join('')||'<p class="mu">No one else yet. Invite friends!</p>'}
function vChat(){shellChat()}
function shellChat(){if(tab!=='chat')return;const ch=[['community','🌍 Community'],...friends().map(i=>[dmRoom(i),'💬 '+nm(people[i])])];
  $('#main').innerHTML=`<div class="chips">${ch.map(([k,l])=>`<span class="chip ${room===k?'on':''}" data-room="${esc(k)}">${esc(l)}</span>`).join('')}</div><div class="card"><div class="msgs" id="msgs"></div><div class="row" style="margin-top:8px"><label class="btn g" style="cursor:pointer">📷<input type="file" id="cf" accept="image/*" hidden></label><input id="mi" placeholder="Type a message…" style="margin:0" maxlength="1000"><button class="btn" data-act="send">Send</button></div><div class="mu" id="cn"></div></div>`;loadMsgs()}
function paintMsgs(){const b=$('#msgs');if(!b)return;b.innerHTML=msgs.map(m=>`<div class="m ${m.user_id===me.id?'me':''}"><b>${esc(nm(m.profiles||people[m.user_id]))}</b>${esc(m.body)}${att(m.image_url)}<span style="display:block;font-size:10px;opacity:.7">${tm(m.created_at)}</span></div>`).join('')||'<p class="mu">No messages yet. Say hi 👋</p>';b.scrollTop=b.scrollHeight}
